In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
profit = revenue - expenses

In [4]:
print(profit)

[[100 110 120]
 [ 14  20  20]
 [  4   8  10]]


In [5]:
prices_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [6]:
prices_per_unit * units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [7]:
np.dot(prices_per_unit,units)

array([34400, 50000, 64400])